Repository lead-ifal/primeira-contribuicao, pull requests merged in 2022-10, with the labels that each got.

#1 adicionando dados
  jmss23.json
Labels: hacktoberfest-approved

#2 update json file
  gbp1.json
Labels: hacktoberfest-approved

#6 Create jvmg1.json
  jvmg1.json
Labels: hacktoberfest-approved

#7 Adiciona o arquivo JSON para primeira contribuição no Hacktoberfest
  vlll1.json
Labels: hacktoberfest-approved

#10 Create vmss5.json
  vmss5.json
Labels: hacktoberfest-approved

#9 Kbq1
  kbq1.json
Labels: hacktoberfest-approved

#31 yss5 adicionando dados
  yss5.json
Labels: hacktoberfest-approved

#32 create gsss1.json
  gsss1.json
Labels: hacktoberfest-approved

#30 Create asc18.json
  asc18.json
Labels: hacktoberfest-approved

#33 Lbs11
  lbs11.json
Labels: hacktoberfest-approved

#28 Adiciona o arquivo JSON
  bss14.json
Labels: hacktoberfest-approved

#36 adicionar dados
  ms8.json
Labels: hacktoberfest-approved

#26 my commit
  jul10c3s4.json
Labels: hacktoberfest-approved

#25 create gln1.json
  gln1.json
Labels: hacktoberfest-approved

#23 my json file
  LICENSE
  khlo1.json
Labels: hacktoberfest-approved

#22 Create mebl2.json
  mebl2.json
Labels: hacktoberfest-approved

#21 First Branch - ras19
  ras19.json
Labels: hacktoberfest-approved

#41 bom dia, o sol já nasceu lá na fazendinha
  mbfs3.json
Labels: hacktoberfest-approved

#42 mcsp3 comitando
  mcsp3.json
Labels: hacktoberfest-approved

#44 Adicionando arquivo
  lmsf1.json
Labels: hacktoberfest-approved

#46 Create lrs20.json
  lrs20.json
Labels: hacktoberfest-approved

#55 add dados
  jfs55.json
Labels: hacktoberfest-accepted

#50 incluindo meus dados
  cls16.json
Labels: hacktoberfest-accepted

#51 Add Dados
  mlsl5.json
Labels: hacktoberfest-accepted

#53 add.dados.ev
  eks3.json
Labels: hacktoberfest-accepted

#54 add cebs1.json
  cebs1.json
Labels: hacktoberfest-accepted

#56 Adicionando arquivo
  jpos2.json
Labels: hacktoberfest-accepted

#58 adicionando dados
  bp1.json
Labels: hacktoberfest-accepted

#59 Adicionando Arquivo
  scs8.json
Labels: hacktoberfest-accepted

#60 Adicionando Arquivo
  klp1.json
Labels: hacktoberfest-accepted

#61 Add my personal info into a json file.
  khs1.json
Labels: hacktoberfest-accepted

#62 phbj1
  phbj1.json
Labels: hacktoberfest-accepted

#63 ADICIONANDO ARQUIVOS
  rms12.json
Labels: hacktoberfest-accepted

#64 commit
  mas55.json
Labels: hacktoberfest-accepted

#66 ADICIONADO_ARQUVO
  rms16.json
Labels: hacktoberfest-accepted

#67 Adicionando novo arquivo
  blgs2.json
Labels: hacktoberfest-accepted

#74 Contribuição
  nasb1.json
Labels: hacktoberfest-accepted

#75 Primeira Contribuição
  tss39.json
Labels: hacktoberfest-accepted

#76 adicionando json
  hkbss1.json
Labels: hacktoberfest-accepted

#78 Jose
  jmesn1.json
Labels: hacktoberfest-accepted

#79 @Rafaelbarros20
  rsb8.json
Labels: hacktoberfest-accepted

#81 Cern1
  cern1.json
Labels: hacktoberfest-accepted

#82 FIRST COMMIT
  tgc1.json
Labels: hacktoberfest-accepted

#83 Add mmms2.json
  mmms2.json
Labels: hacktoberfest-accepted

#84 my first commit
  ahfss1.json
Labels: hacktoberfest-accepted

#87 Create gjs8.json
  gjs8.json
Labels: hacktoberfest-accepted

#88 Create leml1.json
  leml1.json
Labels: hacktoberfest-accepted

#90 adicionei meus dados
  cmmr1.json
Labels: hacktoberfest-accepted

#89 JMRC1
  jmrc1.json
Labels: hacktoberfest-accepted

#100 Add acfr1.json file
  acfr1.json
Labels: hacktoberfest-accepted

#99 Create Smili
  jgss1.json
Labels: good first issue

#97 feat: update
  ermm1.json
Labels: hacktoberfest-accepted

#93 meu primeiro commit
  ghcl1.json
Labels: hacktoberfest-accepted

#111 Create lenl1.json
  lenl1.json
Labels: hacktoberfest-accepted

#106 feat: update
  kofm2.json
Labels: hacktoberfest-accepted

#107 Create cars1.json
  cars1.json
Labels: hacktoberfest-accepted

#108 Tbs11
  tbs11.json
Labels: hacktoberfest-accepted

#113 Added mmss5.json
  mmss5.json
Labels: hacktoberfest-accepted

#118 add json
  jvlo.json
Labels: hacktoberfest-accepted

#124 primeiro commit
  deps1.json
Labels: hacktoberfest-accepted

#117 create aluno joaovt json
  jvml2.json
Labels: hacktoberfest-accepted

#115 Alterações realizadas com sucesso
  jsgj1.json
Labels: hacktoberfest-accepted

#123 add tjos1.json
  tjos1.json
Labels: hacktoberfest-accepted

#122 Create tjbl1.json
  tjlb1.json
Labels: hacktoberfest-accepted

#116 Add m4.json file
  m4.json
Labels: hacktoberfest-accepted

#114 Jhsl2
  jhsl2.json
Labels: hacktoberfest-accepted

#112 Add files via upload
  wvt1.json
Labels: hacktoberfest-accepted

#110 Create abom2.json
  abom2.json
Labels: hacktoberfest-accepted

#109 add info for gabriel soares
  agsss1.json
Labels: hacktoberfest-accepted

#105 Create tkn1.json
  tkn1.json
Labels: hacktoberfest-accepted

#85 Create rag2.json
  rag2.json
Labels: hacktoberfest-accepted

#91 Create fts3.json
  fts3.json
Labels: hacktoberfest-accepted

#92 Create maul1.json
  maul1.json
Labels: hacktoberfest-accepted

#94 adicionei meus dados
  vrs15.json
Labels: hacktoberfest-accepted

#95 adiciona eu
  mcsl9.json
Labels: hacktoberfest-accepted

#96 minha primeira contribuição
  scs9.json
Labels: hacktoberfest-accepted

#98 inseri os dados relacionados a mim e a turma
  nlcs2.json
Labels: hacktoberfest-accepted

#104 add dss66.json
  dss66.json
Labels: hacktoberfest-accepted

#103 Create js38.json
  js38.json
Labels: hacktoberfest-accepted

#101 Minha primeira contribuição no Hacktoberfest
  dps8.json
Labels: hacktoberfest-accepted

#102 Add informações
  jls32.json
Labels: hacktoberfest-accepted

#141 Create msrl1.json
  msrl1.json
Labels: hacktoberfest-accepted

#140 add iplg1.json
  iplg1.json
Labels: hacktoberfest-accepted

#143 minha contribuição
  cegc1.json
Labels: hacktoberfest-accepted

#142 add file
  jvlb2.json
Labels: hacktoberfest-accepted

#139 Primeiro pull request - jlss14
  jlss14.json
Labels: hacktoberfest-accepted

#137 add info Cleber Rian
  crfs5.json
Labels: hacktoberfest-accepted

#136 Create mhs4.json
  mhs4.json
Labels: hacktoberfest-accepted

#134 jfs65
  jfs65.json
Labels: hacktoberfest-accepted

#133 minha primeira contribuição
  jap4.json
Labels: hacktoberfest-accepted

#132 minha primeira contribuição
  jvarb1.json
Labels: hacktoberfest-accepted

#131 add json wls10
  wls10.json
Labels: hacktoberfest-accepted

#129 Create bsoa1.json
  bsoa1.json
Labels: hacktoberfest-accepted

#128 add file json is8.json
  is8.json
Labels: hacktoberfest-accepted

#127 branch da primeira contribuicao
  leab1.json
Labels: hacktoberfest-accepted

#126 ADD SRO3
  sro3.json
Labels: hacktoberfest-accepted

#125 First contribution
  jdgs1
Labels: hacktoberfest-accepted

#147 lpc3
  lpc3.json
Labels: hacktoberfest-accepted

#146 delf1
  delf1.json
Labels: hacktoberfest-accepted

#145 Add info for myself
  ifr1.json
Labels: hacktoberfest-accepted

#144 adicionei o arquivo lmsl3.json
  lmsl3.json
Labels: hacktoberfest-accepted

#149 Create evvt1.json
  evvt1.json
Labels: hacktoberfest-accepted

#150 code.anna
  acfl1.json
Labels: hacktoberfest-accepted
